services:
  api:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db: 
    build:
      context: ./db
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres_data:
