services: 
  api: 
    image: ./docker/Dockerfile.app
    ports:
      - 8000:8000
    depends_on:
      - db

  db: 
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

volumes:
  postgres_data:
