name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Remove old docker images
      run: sudo docker rmi hotapd/nginx-prod hotapd/fastapi-prod -f

    - name: Run new containers
      run: sudo docker compose -f ~/prod/Docker-compose.prod.yml up -d --build
